/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // 웹 애플리케이션으로 빌드
    war

    // java 플러그인은 war가 이미 포함하고 있을 수 있어서 명시
    java

    // Gretty 플러그인을 추가해 내장 Tomcat 사용
    id("org.gretty") version "4.1.10"

    // main() 실행용
    id("application")
}

application {
    mainClass.set("dev.aloc.spring.App")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("org.eclipse.jetty:jetty-server:11.0.26")
    implementation("org.eclipse.jetty:jetty-servlet:11.0.24")
    implementation("org.slf4j:slf4j-simple:2.0.9")

    // Servler API는 웹서버가 제공
    compileOnly("jakarta.servlet:jakarta.servlet-api:6.0.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

gretty {
    contextPath = "/" // contextPath를 'app' 대신 '/' (루트)로 강제 설정
}
